[package]
name = "dreip-backend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.0.1"
serde = "1.0.130"
phonenumber = "0.3.1"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["secrets"]
