[workspace]
members = ["backend_test", "protocol"]

[package]
name = "dreip-backend"
version = "0.1.0"
authors = ["Chris Riches", "Christian Dunn"]
edition = "2021"
description = "Backend server for our DRE-ip based voting system"
readme = "README.md"
repository = "https://github.com/DRE-ip-Implementation-Team/dre-ip-backend"
license = "GNU AGPLv3"
default-run = "dreip-backend"

# Extra binary definition for the verification tool; the server itself
# is auto-detected.
[[bin]]
name = "verification-cli"
path = "src/verification-cli.rs"
required-features = ["verification"]

[features]
default = ["otp"]
otp = []                # Enable authenticated voter sign-in (on by default)
verification = ["clap"] # Enable extra dependencies needed for verification tool compilation

[dependencies]
aws-config = "0.49.0"
aws-sdk-sns = "0.19.0"
aws-types = "0.49.0"
data-encoding = "2.3.2"
hmac = "0.12.1"
jsonwebtoken = "8.1.1"
log = "0.4.17"
log4rs = "1.1.1"
log4rs_dynamic_filters = "0.1.0"
phonenumber = "0.3.1"
rand = "0.8.5"
rust-argon2 = "1.0.0"
serde = "1.0.144"
serde_repr = "0.1.9"
serde_unit_struct = "0.1.1"
sha2 = "0.10.6"
thiserror = "1.0.37"
time = "0.3.14"
typenum = "1.15.0"

[dependencies.chrono]
version = "0.4.22"
features = ["serde"]

[dependencies.clap]
version = "4.0.8"
optional = true # Only needed by verification tool
features = ["cargo", "wrap_help"]

[dependencies.dre-ip]
path = "protocol" # Provided via git submodule

[dependencies.generic-array]
version = "0.14.6" # Need same version as `crypto-common`
features = ["serde"]

[dependencies.mongodb]
version = "2.3.0"
features = ["bson-chrono-0_4"]

[dependencies.reqwest]
version = "0.11.12"
features = ["json"]

[dependencies.rocket]
version = "=0.5.0-rc.2"
features = ["secrets", "json"]

[dev-dependencies.backend-test]
path = "backend_test"

[dev-dependencies.log4rs_test_utils]
version = "0.2.0"
default-features = false
features = ["test_logging"]
