[package]
name = "dreip-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.130"
phonenumber = "0.3.1"
jsonwebtoken = "7.2.0"
thiserror = "1.0.30"
rand = "0.8.4"
time = "0.2.11"
serde_repr = "0.1"
rust-argon2 = "0.8"

[dependencies.rocket]
version = "=0.5.0-rc.1"
features = ["secrets", "json"]

[dependencies.mongodb]
version = "2.0.1"
features = ["bson-chrono-0_4"]

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dev-dependencies]
backend-test = { path = "backend_test" }
