[package]
name = "dreip-backend"
version = "0.1.0"
edition = "2021"
default-run = "dreip-backend"

[[bin]]
name = "verification-cli"
path = "src/verification-cli.rs"
required-features = ["verification"]

[features]
default = ["otp"]
otp = []
verification = ["clap"]

[dependencies]
serde = "1.0.130"
phonenumber = "0.3.1"
jsonwebtoken = "7.2.0"
thiserror = "1.0.30"
rand = "0.8.4"
time = "0.2.11"
serde_repr = "0.1"
serde_unit_struct = "0.1"
rust-argon2 = "0.8"
aws-config = "0.6.0"
aws-sdk-sns = "0.6.0"
hmac = "0.12.1"
sha2 = "0.10.2"
typenum = "1.15.0"

[dependencies.dre-ip]
path = "protocol"

[dependencies.rocket]
version = "=0.5.0-rc.1"
features = ["secrets", "json"]

[dependencies.mongodb]
version = "2.0.1"
features = ["bson-chrono-0_4"]

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.generic-array]
version = "0.14.4" # Need same version as `crypto-common`
features = ["serde"]

[dependencies.clap]
version = "3.0.10"
optional = true
default_features = false
features = ["cargo", "std"]

[dev-dependencies]
backend-test = { path = "backend_test" }
